### PR TITLE
IL - After Carrying Capacity is added to backend, add it to the AdminListCommons page

### LINKED ISSUE #58: After Carrying Capacity is added to backend, add it to the AdminListCommons page
Add CarryingCapacity to CommonsTable.js and AdminListCommonPage.js so that the Carrying Capacity can be seen on those pages.

### PR DESCRIPTION
**Pull request by ilai-ucsb**
In this PR, the field "Carrying Capacity" is added to the table that is displayed in AdminListCommonsPage. 

Storybook link: 
https://ucsb-cs156-f22.github.io/f22-7pm-happycows-docs-qa/storybook-qa/Ian-UpdateAdminListCommonPage

Below is storybook screenshots:
image

image

image

closes #58

### CODE REVIEW

**Review by blakerandle — APPROVED** [review]
lgtm

**Review by wesleykam — DISMISSED** [review]
lgtm!

**Review by ethwu — APPROVED** [review]

**Review by RAILGUN1124 — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM... will merge after testing and getting green on CI/CD

**Pull request merged**
