### PR TITLE
pc/ry/ag - add userCommons plus endpoint to make username available on leaderboard

### PR DESCRIPTION
**Pull request by pconrad**
We add a column to show all the usernames on leaderboard. Close https://github.com/ucsb-cs156-f22/f22-7pm-happycows/issues/22, fix https://github.com/ucsb-cs156-f22/f22-7pm-happycows/pull/37 merge issue, rewrite the code on a fresh copy of main, fix the duplicate data storing issue in https://github.com/ucsb-cs156-f22/f22-7pm-happycows/pull/37#discussion_r1034173414

截屏2022-11-30 19 42 02

### CODE REVIEW

**Comment by ruiqiRichard** [comment]
Close #22, fix #37 merge issue, rewrite the code on a fresh copy of main, fix the duplicate data storing issue in #37: https://github.com/ucsb-cs156-f22/f22-7pm-happycows/pull/37#discussion_r1034173414

**Review by FinalGale — APPROVED** [review]
LGTM

**Review by RAILGUN1124 — APPROVED** [review]
lgtm

**Review by spartan105 — APPROVED** [review]
LGTM

**Comment by tkumar07** [comment]
LGTM

**Pull request merged**
