### PR TITLE
Archit_RY-username col leaderboard fix

### LINKED ISSUE #22: Add column called username to leaderboard that maps user id to the correct username

### PR DESCRIPTION
**Pull request by ruiqiRichard**
Close #22, fix #37 merge issue, restore things deleted by mistake, make a fresher copy of main

### CODE REVIEW

**Comment by ruiqiRichard** [comment]
Still working on the username reference issue: https://github.com/ucsb-cs156-f22/f22-7pm-happycows/pull/37#discussion_r1034173414

**Review by FinalGale — APPROVED** [review]
LGTM

**Review by FinalGale — CHANGES_REQUESTED** [review]
Richard is still working on the username reference issue

**Comment by spartan105** [comment]
> Still working on the username reference issue: [#37 (comment)](https://github.com/ucsb-cs156-f22/f22-7pm-happycows/pull/37#discussion_r1034173414)

I think we should leave it as it is. not sure how we can access the data from the user class

**Review by spartan105 — COMMENTED** [review]
LGTM

**Comment by ruiqiRichard** [comment]
issues get fixed in #65

**Pull request closed without merging**
