### PR TITLE
Removed "The game will end on"

### PR DESCRIPTION
**Pull request by FinalGale**
This closes issue #39 
image

### CODE REVIEW

**Review by blakerandle — CHANGES_REQUESTED** [review]
It seems the issue only wants to the remove the "This game will end on _." text, but the "Today is day _!" text is also removed in this PR. I think it should be added back

**Review by blakerandle — COMMENTED** [review]
These changes now lgtm. I understand the tests are failing due to the main branch's frontend tests failing, so this PR should probably be checked again after the main branch's tests are addressed and those fixes are merged into this branch.

**Review by RAILGUN1124 — APPROVED** [review]
lgtm

**Review by blakerandle — APPROVED** [review]
lgtm!

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
