### PR TITLE
Fixed bug Toast says "Cow bought" even when no cow was bought

### LINKED ISSUE #19: FIX BUG: Toast says "Cow Bought" even when no cow was bought
Overview
When buying cows, if you run out of money, the app doesn't let you continue to buy cows. However, the toast message that pops up says "Cow Bought" even if you didn't just buy a cow.

Perhaps the toast should NOT pop up when you successfully buy a cow (since you already see the number of cows go up, and your money go down), but should ONLY pop up when you are out of money and try to buy a cow.. and in that case, the message should indicate that.

Steps to reproduce
1. Join a commons
2. Try to buy cows until you run out of money. See toasts that say "Cow Bought"
3. Try to buy another cow
Expected: a toast that says something like: "You can't buy a cow because you don't have enough money"
Observed: a toast that says "Cow Bought"

https://user-images.githubusercontent.com/1119017/203444338-f29c6288-aa5e-4715-aca3-0bbecdb75ac5.gif

### PR DESCRIPTION
**Pull request by minhbui27**
In this commit, I modified the PlayPage.js to include a condition that checks whether a cow can be bought anymore, if this condition is not satisfied i.e no more cows can be bought then the "Cow Bought!" dialog will not print.
Closes #19 

Animation

### CODE REVIEW

**Review by ilai-ucsb — DISMISSED** [review]
image
There should be a statement that tells the user they cannot buy anymore cows because they don't have enough money.

**Comment by minhbui27** [comment]
> image There should be a statement that tells the user they cannot buy anymore cows because they don't have enough money.

You are right i forgo

**Review by ilai-ucsb — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM.   I'm surprised that Stryker didn't require a test for this, but since it didn't, we'll let that slide.

**Pull request merged**
