### PR TITLE
IL - After Carrying Capacity added to backend (issue #13), add it to the frontend Create / Update operations

### LINKED ISSUE #61: After Carrying Capacity added to backend (issue #13), add it to the frontend Create / Update operations
Once CarryingCapacity is added to the frontend, add CarryingCapacity to the create and update operations here:

- CommonsForm.js, AdminCreateCommonsPage.js, AdminEditCommonsPage.js

### PR DESCRIPTION
**Pull request by ilai-ucsb**
In this PR I added carrying capacity to the frontend create (AdminCreateCommonsPage) and edit form (when an admin clicks on the edit button).

Storybook link:
https://ucsb-cs156-f22.github.io/f22-7pm-happycows-docs-qa/storybook-qa/Ian-UpdateAdminCreate-EditPage

Updated form screenshot:
image

closes #61

### CODE REVIEW

**Review by RAILGUN1124 — DISMISSED** [review]
lgtm

**Review by KaieChen — DISMISSED** [review]
Looks good to me! Though I am wondering why this change was necessary.
Screen Shot 2022-11-30 at 3 58 22 PM

**Comment by ilai-ucsb** [comment]
> Looks good to me! Though I am wondering why this change was necessary. Screen Shot 2022-11-30 at 3 58 22 PM

It was necessary to get storybook to run properly otherwise it kept on throwing an error.

**Review by RAILGUN1124 — DISMISSED** [review]
lgtm

**Review by KaieChen — DISMISSED** [review]
lgtm!

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
