### PR TITLE
Calculate days elapsed

### PR DESCRIPTION
**Pull request by FinalGale**
This closes issue #44 and the image shows it working on Heroku QA
image

### CODE REVIEW

**Review by RAILGUN1124 — DISMISSED** [review]
lgtm

**Review by ruiqiRichard — DISMISSED** [review]
LGTM

**Review by RAILGUN1124 — APPROVED** [review]
lgtm

**Comment by ruiqiRichard** [comment]
Deploying: sheila-pr-37-add-cow-death-controller
PR https://github.com/ucsb-cs156-f22/f22-7pm-happycows/pull/63
on QAs site; https://dashboard.heroku.com/apps/f22-7pm-4-happycows-qa
Build Progress: https://dashboard.heroku.com/apps/f22-7pm-4-happycows-qa/activity/builds/f3f44ad0-d359-4d33-91a5-b474981f17d9

**Review by pconrad — APPROVED** [review]
As long as it passes CI/CD, LGTM

**Pull request merged**
